version: '3.9'

services:
 lsplanner-redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_REPLICATION_NODE_ID=1
      - REDIS_REPLICATION_NODE_ADDRESS=lsplanner-redis:6379
      - REDIS_REPLICATION_NODE_MASTER_AUTH=lsplanner

 lsplanner-database:
    image: "postgres:alpine"
    environment:
      POSTGRES_DB: lsplanner
      POSTGRES_USER: lsplanner
      POSTGRES_PASSWORD: lsplanner
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lsplanner"]
      interval: 5s
      timeout: 5s
      retries: 5

 lsplanner-go-service:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/code
    depends_on:
      lsplanner-database:
        condition: service_healthy
    environment:
      - REDIS_URL=lsplanner-redis:6379
      - REDIS_PASSW=lsplanner
