version: '3.9'

services:
 lsplanner-redis:
    image: "redis:alpine"

 lsplanner-database:
    image: "postgres:alpine"
    environment:
      POSTGRES_DB: lsplanner
      POSTGRES_USER: lsplanner
      POSTGRES_PASSWORD: lsplanner
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lsplanner"]
      interval: 5s
      timeout: 5s
      retries: 5

 lsplanner-go-service:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/code
    depends_on:
      lsplanner-database:
        condition: service_healthy
